openapi: 3.0.0
info:
  title: Mock API
  version: 1.0.0
paths:
  /test:
    get:
      summary: 테스트용 응답
      responses:
        '200':
          description: 성공 응답
          content:
            application/json:
              example:
                message: "Hello from Mock Server"
